name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "pypy3.9"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox pytest-cov .
    - name: Test
      run: |
        coverage run --branch --source=pytest_unordered -m pytest tests/
        coverage xml -o ./coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
        files: ./coverage.xml
        verbose: true
